"""Curve state models."""

from curves.curve_state import (
    CurveCollection,
    CurveProcessingError,
    CurveRepairError,
    DEFAULT_CURVE_REPAIR_TOLERANCE,
    DEFAULT_CURVE_SIMPLIFY_TOLERANCE,
    DEFAULT_CURVE_SMOOTH_ITERATIONS,
    StoredCurve,
    add_curve,
    auto_close_curve,
    clear_curves_for_plane,
    clear_curves_for_section_result,
    clear_curve_selection,
    get_selected_curves,
    get_tiny_curves,
    get_visible_curves,
    is_repaired_curve,
    join_curves,
    refresh_curve_diagnostics,
    remove_curve,
    set_active_curve,
    set_selected_curves,
    simplify_curve,
    smooth_curve,
)

__all__ = [
    "CurveCollection",
    "CurveProcessingError",
    "CurveRepairError",
    "DEFAULT_CURVE_REPAIR_TOLERANCE",
    "DEFAULT_CURVE_SIMPLIFY_TOLERANCE",
    "DEFAULT_CURVE_SMOOTH_ITERATIONS",
    "StoredCurve",
    "add_curve",
    "auto_close_curve",
    "clear_curve_selection",
    "clear_curves_for_plane",
    "clear_curves_for_section_result",
    "get_selected_curves",
    "get_tiny_curves",
    "get_visible_curves",
    "is_repaired_curve",
    "join_curves",
    "refresh_curve_diagnostics",
    "remove_curve",
    "set_active_curve",
    "set_selected_curves",
    "simplify_curve",
    "smooth_curve",
]
