"""Surface state models."""

from surfaces.brep_state import (
    BREP_TYPE_LOFT_SURFACE,
    BREP_TYPE_PLANAR_FACE,
    BREP_TYPE_UNKNOWN,
    BREP_TYPES,
    BrepSurfaceCollection,
    BrepSurfaceRecord,
    add_brep_surface,
    clear_brep_surface_selection,
    get_active_brep_surface,
    get_visible_brep_surfaces,
    remove_brep_surface,
    set_active_brep_surface,
    set_selected_brep_surfaces,
)
from surfaces.surface_state import (
    SurfaceCollection,
    SurfacePatch,
    add_surface,
    clear_surface_selection,
    clear_surfaces_for_curve,
    get_active_surface,
    get_visible_surfaces,
    remove_surface,
    set_active_surface,
    set_selected_surfaces,
)
from surfaces.surface_preview import (
    BOUNDARY_PATCH,
    CLOSED_CURVE_FILL,
    CURVE_NETWORK_PATCH,
    FOUR_CURVE_PATCH,
    SurfacePreviewBuildResult,
    SurfacePreviewMesh,
    TWO_CURVE_LOFT,
    build_boundary_patch_preview,
    build_curve_network_patch_preview,
    build_four_curve_patch_preview,
    build_surface_preview,
    build_surface_preview_mesh,
)
from surfaces.loft_feature import LoftFeatureCollection, LoftFeatureOptions, LoftFeatureRecord
from surfaces.four_boundary_feature import (
    FourBoundaryPatchFeatureCollection,
    FourBoundaryPatchFeatureRecord,
)

__all__ = [
    "BREP_TYPE_LOFT_SURFACE",
    "BREP_TYPE_PLANAR_FACE",
    "BREP_TYPE_UNKNOWN",
    "BREP_TYPES",
    "BOUNDARY_PATCH",
    "CLOSED_CURVE_FILL",
    "CURVE_NETWORK_PATCH",
    "FOUR_CURVE_PATCH",
    "FourBoundaryPatchFeatureCollection",
    "FourBoundaryPatchFeatureRecord",
    "BrepSurfaceCollection",
    "BrepSurfaceRecord",
    "LoftFeatureCollection",
    "LoftFeatureOptions",
    "LoftFeatureRecord",
    "SurfaceCollection",
    "SurfacePreviewBuildResult",
    "SurfacePatch",
    "SurfacePreviewMesh",
    "TWO_CURVE_LOFT",
    "add_brep_surface",
    "add_surface",
    "build_boundary_patch_preview",
    "build_curve_network_patch_preview",
    "build_four_curve_patch_preview",
    "build_surface_preview",
    "build_surface_preview_mesh",
    "clear_brep_surface_selection",
    "clear_surface_selection",
    "clear_surfaces_for_curve",
    "get_active_brep_surface",
    "get_active_surface",
    "get_visible_brep_surfaces",
    "get_visible_surfaces",
    "remove_brep_surface",
    "remove_surface",
    "set_active_brep_surface",
    "set_selected_brep_surfaces",
    "set_active_surface",
    "set_selected_surfaces",
]
