"""Surface state models."""

from surfaces.surface_state import (
    SurfaceCollection,
    SurfacePatch,
    add_surface,
    clear_surface_selection,
    clear_surfaces_for_curve,
    get_active_surface,
    get_visible_surfaces,
    remove_surface,
    set_active_surface,
    set_selected_surfaces,
)
from surfaces.surface_preview import (
    BOUNDARY_PATCH,
    CLOSED_CURVE_FILL,
    CURVE_NETWORK_PATCH,
    FOUR_CURVE_PATCH,
    SurfacePreviewBuildResult,
    SurfacePreviewMesh,
    TWO_CURVE_LOFT,
    build_boundary_patch_preview,
    build_curve_network_patch_preview,
    build_four_curve_patch_preview,
    build_surface_preview,
    build_surface_preview_mesh,
)

__all__ = [
    "BOUNDARY_PATCH",
    "CLOSED_CURVE_FILL",
    "CURVE_NETWORK_PATCH",
    "FOUR_CURVE_PATCH",
    "SurfaceCollection",
    "SurfacePreviewBuildResult",
    "SurfacePatch",
    "SurfacePreviewMesh",
    "TWO_CURVE_LOFT",
    "add_surface",
    "build_boundary_patch_preview",
    "build_curve_network_patch_preview",
    "build_four_curve_patch_preview",
    "build_surface_preview",
    "build_surface_preview_mesh",
    "clear_surface_selection",
    "clear_surfaces_for_curve",
    "get_active_surface",
    "get_visible_surfaces",
    "remove_surface",
    "set_active_surface",
    "set_selected_surfaces",
]
